# Generated by Django 6.0.6 on 2026-06-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_texto', models.TextField()),
                ('pagina_origen', models.SmallIntegerField()),
                ('chunk_index', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documentos_rag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_ingresado', models.TextField()),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('tokens_procesados', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log_consultas',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('titulo', models.CharField(max_length=350)),
                ('autor', models.CharField(max_length=250)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('tecnologias', models.JSONField(default=list)),
                ('promocion', models.CharField(max_length=10)),
                ('estado', models.CharField(default='En Revisión', max_length=20)),
                ('ruta_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('similitud_maxima', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(default='CHANGEME', max_length=255)),
                ('rol', models.CharField(default='docente', max_length=10)),
                ('codigo_docente', models.CharField(max_length=20, null=True, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
